dataset:
  train_dataset_path: ./dataset/train.csv
  test_dataset_path: ./dataset/test.csv 

cors:
  url_react: http://localhost:3000

jwt:
  secret_key: super-strong-random-key
  access_token_expire_time: 1
  jwt_token_location: cookies
  jwt_cookie_secure: False #must be False for localhost
  jwt_cookie_samesite: LAX #"None" only if you’re mixing domains in production
  jwt_cookie_csrf_protect: False #Decides whether you want to do the verification usin gcsrf token or not
